
### Register a user POST /AUTH/REGISTER
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "alsojulha",
    "password": "123123123",
    "wallet": "cXjbRGENz4kNpDJPGn8mpYmW8XXrXMaHgep86fC1eK4XMegTK"
}


### Debug DB
GET http://localhost:5003/file/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyNDcxMzU4LCJleHAiOjE3NjI1NTc3NTh9.EDopzUv-zqaCrhczUpfwolKThP3I7iNxe4gtaRLUeUE

### Login a user POST /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "joao",
    "password": "123123123"
}
